apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: techzoneisn023/python-job
        name: app
        ports:
        - containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
 name: app-service
spec:
 type: NodePort
 selector:
    app: app
 ports:
    - protocol: TCP
      port: 80
      targetPort: 4004
      nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: myapp-ingress
spec:
 rules:
 - host: app.local.host
   http:
     paths:
     - path: /api
       pathType: Prefix
       backend:
         service:
           name: app-service
           port:
             number: 80
